### ISSUE TITLE
Sirene NPC for Baldur's Gate: Siege of Dragonspear, parse error

### ISSUE THREAD

**Issue by willardthor** [ArtemiusI/Sirene-NPC#1]
Hi ArtemiusI,

While modding my BG1 (preparing it for EET), I got an error when installing your Sirene mod, specifically the part that adds dialog in Siege of Dragonspear. Here's my debug file:

[SETUP-SIRENE.DEBUG.txt](https://github.com/ArtemiusI/Sirene-NPC/files/537255/SETUP-SIRENE.DEBUG.txt)

**Comment by TheArtisanBG** [comment]
Weird. Looks like it can't find your SoD content for whatever reason. What directory are you installing the mod in?

**Comment by willardthor** [comment]
... ah. I forgot to run modmerge (I installed BG1 through Steam). Consider
the matter resolved (I'll come back if that doesn't resolve the issue).
